### ISSUE TITLE
Media Query Not Breaking Correctly for Sidebar

### ISSUE THREAD

**Issue by scoarescoare** [rdash/rdash-angular#93]
When I resize my browser, I expect the left sidebar to shrink when the viewport reaches `561px`.

```css
@media only screen and (min-width: 561px) {
    #page-wrapper.open {
        padding-left:250px
    }
}
```

The css media query associated with `#page-wrapper` is not used because `#page-wrapper` is controlled by `toggle`, a property defined on the `master-ctrl`.

```html
<div id="page-wrapper" ng-class="{'open': toggle}" class="open">
```

It would make sense to alleviate this confusion by either removing the css media query or adjusting the `ng-class` logic.
